// Generated by gencpp from file nao_matador/Detection_msg.msg
// DO NOT EDIT!


#ifndef NAO_MATADOR_MESSAGE_DETECTION_MSG_H
#define NAO_MATADOR_MESSAGE_DETECTION_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nao_matador
{
template <class ContainerAllocator>
struct Detection_msg_
{
  typedef Detection_msg_<ContainerAllocator> Type;

  Detection_msg_()
    : aruco_detection(false)
    , bull_detection(false)  {
    }
  Detection_msg_(const ContainerAllocator& _alloc)
    : aruco_detection(false)
    , bull_detection(false)  {
  (void)_alloc;
    }



   typedef uint8_t _aruco_detection_type;
  _aruco_detection_type aruco_detection;

   typedef uint8_t _bull_detection_type;
  _bull_detection_type bull_detection;





  typedef boost::shared_ptr< ::nao_matador::Detection_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nao_matador::Detection_msg_<ContainerAllocator> const> ConstPtr;

}; // struct Detection_msg_

typedef ::nao_matador::Detection_msg_<std::allocator<void> > Detection_msg;

typedef boost::shared_ptr< ::nao_matador::Detection_msg > Detection_msgPtr;
typedef boost::shared_ptr< ::nao_matador::Detection_msg const> Detection_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nao_matador::Detection_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nao_matador::Detection_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nao_matador

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nao_matador': ['/home/nao/group_b_final_project/devel/share/nao_matador/msg', '/home/nao/group_b_final_project/src/nao_matador/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nao_matador::Detection_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nao_matador::Detection_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nao_matador::Detection_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nao_matador::Detection_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nao_matador::Detection_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nao_matador::Detection_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nao_matador::Detection_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3c2f57bd512b4cbd9a0998ce883e34fd";
  }

  static const char* value(const ::nao_matador::Detection_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3c2f57bd512b4cbdULL;
  static const uint64_t static_value2 = 0x9a0998ce883e34fdULL;
};

template<class ContainerAllocator>
struct DataType< ::nao_matador::Detection_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nao_matador/Detection_msg";
  }

  static const char* value(const ::nao_matador::Detection_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nao_matador::Detection_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool aruco_detection\n\
bool bull_detection\n\
";
  }

  static const char* value(const ::nao_matador::Detection_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nao_matador::Detection_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.aruco_detection);
      stream.next(m.bull_detection);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Detection_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nao_matador::Detection_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nao_matador::Detection_msg_<ContainerAllocator>& v)
  {
    s << indent << "aruco_detection: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.aruco_detection);
    s << indent << "bull_detection: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.bull_detection);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAO_MATADOR_MESSAGE_DETECTION_MSG_H
