// Generated by gencpp from file nao_matador/Led_msgsRequest.msg
// DO NOT EDIT!


#ifndef NAO_MATADOR_MESSAGE_LED_MSGSREQUEST_H
#define NAO_MATADOR_MESSAGE_LED_MSGSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nao_matador
{
template <class ContainerAllocator>
struct Led_msgsRequest_
{
  typedef Led_msgsRequest_<ContainerAllocator> Type;

  Led_msgsRequest_()
    : action()
    , iterations(0.0)  {
    }
  Led_msgsRequest_(const ContainerAllocator& _alloc)
    : action(_alloc)
    , iterations(0.0)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _action_type;
  _action_type action;

   typedef float _iterations_type;
  _iterations_type iterations;





  typedef boost::shared_ptr< ::nao_matador::Led_msgsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nao_matador::Led_msgsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Led_msgsRequest_

typedef ::nao_matador::Led_msgsRequest_<std::allocator<void> > Led_msgsRequest;

typedef boost::shared_ptr< ::nao_matador::Led_msgsRequest > Led_msgsRequestPtr;
typedef boost::shared_ptr< ::nao_matador::Led_msgsRequest const> Led_msgsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nao_matador::Led_msgsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nao_matador::Led_msgsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nao_matador

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nao_matador': ['/home/nao/group_b_final_project/devel/share/nao_matador/msg', '/home/nao/group_b_final_project/src/nao_matador/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nao_matador::Led_msgsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nao_matador::Led_msgsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nao_matador::Led_msgsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nao_matador::Led_msgsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nao_matador::Led_msgsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nao_matador::Led_msgsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nao_matador::Led_msgsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9ad92e46ba6d1a69f6f8be11f4338cd8";
  }

  static const char* value(const ::nao_matador::Led_msgsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9ad92e46ba6d1a69ULL;
  static const uint64_t static_value2 = 0xf6f8be11f4338cd8ULL;
};

template<class ContainerAllocator>
struct DataType< ::nao_matador::Led_msgsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nao_matador/Led_msgsRequest";
  }

  static const char* value(const ::nao_matador::Led_msgsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nao_matador::Led_msgsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
string[] action\n\
float32 iterations\n\
";
  }

  static const char* value(const ::nao_matador::Led_msgsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nao_matador::Led_msgsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action);
      stream.next(m.iterations);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Led_msgsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nao_matador::Led_msgsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nao_matador::Led_msgsRequest_<ContainerAllocator>& v)
  {
    s << indent << "action[]" << std::endl;
    for (size_t i = 0; i < v.action.size(); ++i)
    {
      s << indent << "  action[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.action[i]);
    }
    s << indent << "iterations: ";
    Printer<float>::stream(s, indent + "  ", v.iterations);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAO_MATADOR_MESSAGE_LED_MSGSREQUEST_H
