// Generated by gencpp from file nao_matador/Led_msgs.msg
// DO NOT EDIT!


#ifndef NAO_MATADOR_MESSAGE_LED_MSGS_H
#define NAO_MATADOR_MESSAGE_LED_MSGS_H

#include <ros/service_traits.h>


#include <nao_matador/Led_msgsRequest.h>
#include <nao_matador/Led_msgsResponse.h>


namespace nao_matador
{

struct Led_msgs
{

typedef Led_msgsRequest Request;
typedef Led_msgsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Led_msgs
} // namespace nao_matador


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nao_matador::Led_msgs > {
  static const char* value()
  {
    return "2b911cc642045673cb148a058d46af03";
  }

  static const char* value(const ::nao_matador::Led_msgs&) { return value(); }
};

template<>
struct DataType< ::nao_matador::Led_msgs > {
  static const char* value()
  {
    return "nao_matador/Led_msgs";
  }

  static const char* value(const ::nao_matador::Led_msgs&) { return value(); }
};


// service_traits::MD5Sum< ::nao_matador::Led_msgsRequest> should match 
// service_traits::MD5Sum< ::nao_matador::Led_msgs > 
template<>
struct MD5Sum< ::nao_matador::Led_msgsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nao_matador::Led_msgs >::value();
  }
  static const char* value(const ::nao_matador::Led_msgsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nao_matador::Led_msgsRequest> should match 
// service_traits::DataType< ::nao_matador::Led_msgs > 
template<>
struct DataType< ::nao_matador::Led_msgsRequest>
{
  static const char* value()
  {
    return DataType< ::nao_matador::Led_msgs >::value();
  }
  static const char* value(const ::nao_matador::Led_msgsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nao_matador::Led_msgsResponse> should match 
// service_traits::MD5Sum< ::nao_matador::Led_msgs > 
template<>
struct MD5Sum< ::nao_matador::Led_msgsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nao_matador::Led_msgs >::value();
  }
  static const char* value(const ::nao_matador::Led_msgsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nao_matador::Led_msgsResponse> should match 
// service_traits::DataType< ::nao_matador::Led_msgs > 
template<>
struct DataType< ::nao_matador::Led_msgsResponse>
{
  static const char* value()
  {
    return DataType< ::nao_matador::Led_msgs >::value();
  }
  static const char* value(const ::nao_matador::Led_msgsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAO_MATADOR_MESSAGE_LED_MSGS_H
