// Generated by gencpp from file nao_matador/SetSpeechVocabularyResult.msg
// DO NOT EDIT!


#ifndef NAO_MATADOR_MESSAGE_SETSPEECHVOCABULARYRESULT_H
#define NAO_MATADOR_MESSAGE_SETSPEECHVOCABULARYRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nao_matador
{
template <class ContainerAllocator>
struct SetSpeechVocabularyResult_
{
  typedef SetSpeechVocabularyResult_<ContainerAllocator> Type;

  SetSpeechVocabularyResult_()
    : success(false)  {
    }
  SetSpeechVocabularyResult_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::nao_matador::SetSpeechVocabularyResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nao_matador::SetSpeechVocabularyResult_<ContainerAllocator> const> ConstPtr;

}; // struct SetSpeechVocabularyResult_

typedef ::nao_matador::SetSpeechVocabularyResult_<std::allocator<void> > SetSpeechVocabularyResult;

typedef boost::shared_ptr< ::nao_matador::SetSpeechVocabularyResult > SetSpeechVocabularyResultPtr;
typedef boost::shared_ptr< ::nao_matador::SetSpeechVocabularyResult const> SetSpeechVocabularyResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nao_matador::SetSpeechVocabularyResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nao_matador::SetSpeechVocabularyResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nao_matador

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nao_matador': ['/home/nao/group_b_final_project/devel/share/nao_matador/msg', '/home/nao/group_b_final_project/src/nao_matador/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nao_matador::SetSpeechVocabularyResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nao_matador::SetSpeechVocabularyResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nao_matador::SetSpeechVocabularyResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nao_matador::SetSpeechVocabularyResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nao_matador::SetSpeechVocabularyResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nao_matador::SetSpeechVocabularyResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nao_matador::SetSpeechVocabularyResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::nao_matador::SetSpeechVocabularyResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::nao_matador::SetSpeechVocabularyResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nao_matador/SetSpeechVocabularyResult";
  }

  static const char* value(const ::nao_matador::SetSpeechVocabularyResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nao_matador::SetSpeechVocabularyResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
bool success\n\
";
  }

  static const char* value(const ::nao_matador::SetSpeechVocabularyResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nao_matador::SetSpeechVocabularyResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetSpeechVocabularyResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nao_matador::SetSpeechVocabularyResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nao_matador::SetSpeechVocabularyResult_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAO_MATADOR_MESSAGE_SETSPEECHVOCABULARYRESULT_H
