// Generated by gencpp from file nao_matador/Speaking_msgs.msg
// DO NOT EDIT!


#ifndef NAO_MATADOR_MESSAGE_SPEAKING_MSGS_H
#define NAO_MATADOR_MESSAGE_SPEAKING_MSGS_H

#include <ros/service_traits.h>


#include <nao_matador/Speaking_msgsRequest.h>
#include <nao_matador/Speaking_msgsResponse.h>


namespace nao_matador
{

struct Speaking_msgs
{

typedef Speaking_msgsRequest Request;
typedef Speaking_msgsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Speaking_msgs
} // namespace nao_matador


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nao_matador::Speaking_msgs > {
  static const char* value()
  {
    return "86ef64771475bc1259bdb4cd8317d13b";
  }

  static const char* value(const ::nao_matador::Speaking_msgs&) { return value(); }
};

template<>
struct DataType< ::nao_matador::Speaking_msgs > {
  static const char* value()
  {
    return "nao_matador/Speaking_msgs";
  }

  static const char* value(const ::nao_matador::Speaking_msgs&) { return value(); }
};


// service_traits::MD5Sum< ::nao_matador::Speaking_msgsRequest> should match 
// service_traits::MD5Sum< ::nao_matador::Speaking_msgs > 
template<>
struct MD5Sum< ::nao_matador::Speaking_msgsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nao_matador::Speaking_msgs >::value();
  }
  static const char* value(const ::nao_matador::Speaking_msgsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nao_matador::Speaking_msgsRequest> should match 
// service_traits::DataType< ::nao_matador::Speaking_msgs > 
template<>
struct DataType< ::nao_matador::Speaking_msgsRequest>
{
  static const char* value()
  {
    return DataType< ::nao_matador::Speaking_msgs >::value();
  }
  static const char* value(const ::nao_matador::Speaking_msgsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nao_matador::Speaking_msgsResponse> should match 
// service_traits::MD5Sum< ::nao_matador::Speaking_msgs > 
template<>
struct MD5Sum< ::nao_matador::Speaking_msgsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nao_matador::Speaking_msgs >::value();
  }
  static const char* value(const ::nao_matador::Speaking_msgsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nao_matador::Speaking_msgsResponse> should match 
// service_traits::DataType< ::nao_matador::Speaking_msgs > 
template<>
struct DataType< ::nao_matador::Speaking_msgsResponse>
{
  static const char* value()
  {
    return DataType< ::nao_matador::Speaking_msgs >::value();
  }
  static const char* value(const ::nao_matador::Speaking_msgsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAO_MATADOR_MESSAGE_SPEAKING_MSGS_H
