// Generated by gencpp from file nao_matador/SpeechWithFeedbackFeedback.msg
// DO NOT EDIT!


#ifndef NAO_MATADOR_MESSAGE_SPEECHWITHFEEDBACKFEEDBACK_H
#define NAO_MATADOR_MESSAGE_SPEECHWITHFEEDBACKFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nao_matador
{
template <class ContainerAllocator>
struct SpeechWithFeedbackFeedback_
{
  typedef SpeechWithFeedbackFeedback_<ContainerAllocator> Type;

  SpeechWithFeedbackFeedback_()
    {
    }
  SpeechWithFeedbackFeedback_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::nao_matador::SpeechWithFeedbackFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nao_matador::SpeechWithFeedbackFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct SpeechWithFeedbackFeedback_

typedef ::nao_matador::SpeechWithFeedbackFeedback_<std::allocator<void> > SpeechWithFeedbackFeedback;

typedef boost::shared_ptr< ::nao_matador::SpeechWithFeedbackFeedback > SpeechWithFeedbackFeedbackPtr;
typedef boost::shared_ptr< ::nao_matador::SpeechWithFeedbackFeedback const> SpeechWithFeedbackFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nao_matador::SpeechWithFeedbackFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nao_matador::SpeechWithFeedbackFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nao_matador

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nao_matador': ['/home/nao/group_b_final_project/devel/share/nao_matador/msg', '/home/nao/group_b_final_project/src/nao_matador/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nao_matador::SpeechWithFeedbackFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nao_matador::SpeechWithFeedbackFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nao_matador::SpeechWithFeedbackFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nao_matador::SpeechWithFeedbackFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nao_matador::SpeechWithFeedbackFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nao_matador::SpeechWithFeedbackFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nao_matador::SpeechWithFeedbackFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::nao_matador::SpeechWithFeedbackFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::nao_matador::SpeechWithFeedbackFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nao_matador/SpeechWithFeedbackFeedback";
  }

  static const char* value(const ::nao_matador::SpeechWithFeedbackFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nao_matador::SpeechWithFeedbackFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Empty feedback\n\
\n\
";
  }

  static const char* value(const ::nao_matador::SpeechWithFeedbackFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nao_matador::SpeechWithFeedbackFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SpeechWithFeedbackFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nao_matador::SpeechWithFeedbackFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::nao_matador::SpeechWithFeedbackFeedback_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // NAO_MATADOR_MESSAGE_SPEECHWITHFEEDBACKFEEDBACK_H
