// Generated by gencpp from file nao_matador/SpeechWithFeedbackGoal.msg
// DO NOT EDIT!


#ifndef NAO_MATADOR_MESSAGE_SPEECHWITHFEEDBACKGOAL_H
#define NAO_MATADOR_MESSAGE_SPEECHWITHFEEDBACKGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nao_matador
{
template <class ContainerAllocator>
struct SpeechWithFeedbackGoal_
{
  typedef SpeechWithFeedbackGoal_<ContainerAllocator> Type;

  SpeechWithFeedbackGoal_()
    : say()  {
    }
  SpeechWithFeedbackGoal_(const ContainerAllocator& _alloc)
    : say(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _say_type;
  _say_type say;





  typedef boost::shared_ptr< ::nao_matador::SpeechWithFeedbackGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nao_matador::SpeechWithFeedbackGoal_<ContainerAllocator> const> ConstPtr;

}; // struct SpeechWithFeedbackGoal_

typedef ::nao_matador::SpeechWithFeedbackGoal_<std::allocator<void> > SpeechWithFeedbackGoal;

typedef boost::shared_ptr< ::nao_matador::SpeechWithFeedbackGoal > SpeechWithFeedbackGoalPtr;
typedef boost::shared_ptr< ::nao_matador::SpeechWithFeedbackGoal const> SpeechWithFeedbackGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nao_matador::SpeechWithFeedbackGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nao_matador::SpeechWithFeedbackGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nao_matador

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nao_matador': ['/home/nao/group_b_final_project/devel/share/nao_matador/msg', '/home/nao/group_b_final_project/src/nao_matador/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nao_matador::SpeechWithFeedbackGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nao_matador::SpeechWithFeedbackGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nao_matador::SpeechWithFeedbackGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nao_matador::SpeechWithFeedbackGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nao_matador::SpeechWithFeedbackGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nao_matador::SpeechWithFeedbackGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nao_matador::SpeechWithFeedbackGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "331898fd34308d7c3706d43ca7f6e377";
  }

  static const char* value(const ::nao_matador::SpeechWithFeedbackGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x331898fd34308d7cULL;
  static const uint64_t static_value2 = 0x3706d43ca7f6e377ULL;
};

template<class ContainerAllocator>
struct DataType< ::nao_matador::SpeechWithFeedbackGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nao_matador/SpeechWithFeedbackGoal";
  }

  static const char* value(const ::nao_matador::SpeechWithFeedbackGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nao_matador::SpeechWithFeedbackGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Purpose : To have feedback on when the speech was started and when \n\
# NAO stopped talking\n\
# Goal: The sentence for NAO to say \n\
# Result: NAO has finished speaking\n\
# Feedback: When NAO starts speaking\n\
\n\
string say\n\
";
  }

  static const char* value(const ::nao_matador::SpeechWithFeedbackGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nao_matador::SpeechWithFeedbackGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.say);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SpeechWithFeedbackGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nao_matador::SpeechWithFeedbackGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nao_matador::SpeechWithFeedbackGoal_<ContainerAllocator>& v)
  {
    s << indent << "say: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.say);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAO_MATADOR_MESSAGE_SPEECHWITHFEEDBACKGOAL_H
