// Generated by gencpp from file nao_matador/Walking_msgs.msg
// DO NOT EDIT!


#ifndef NAO_MATADOR_MESSAGE_WALKING_MSGS_H
#define NAO_MATADOR_MESSAGE_WALKING_MSGS_H

#include <ros/service_traits.h>


#include <nao_matador/Walking_msgsRequest.h>
#include <nao_matador/Walking_msgsResponse.h>


namespace nao_matador
{

struct Walking_msgs
{

typedef Walking_msgsRequest Request;
typedef Walking_msgsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Walking_msgs
} // namespace nao_matador


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nao_matador::Walking_msgs > {
  static const char* value()
  {
    return "24f4c0c158be28ca805fda0236382fd4";
  }

  static const char* value(const ::nao_matador::Walking_msgs&) { return value(); }
};

template<>
struct DataType< ::nao_matador::Walking_msgs > {
  static const char* value()
  {
    return "nao_matador/Walking_msgs";
  }

  static const char* value(const ::nao_matador::Walking_msgs&) { return value(); }
};


// service_traits::MD5Sum< ::nao_matador::Walking_msgsRequest> should match 
// service_traits::MD5Sum< ::nao_matador::Walking_msgs > 
template<>
struct MD5Sum< ::nao_matador::Walking_msgsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nao_matador::Walking_msgs >::value();
  }
  static const char* value(const ::nao_matador::Walking_msgsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nao_matador::Walking_msgsRequest> should match 
// service_traits::DataType< ::nao_matador::Walking_msgs > 
template<>
struct DataType< ::nao_matador::Walking_msgsRequest>
{
  static const char* value()
  {
    return DataType< ::nao_matador::Walking_msgs >::value();
  }
  static const char* value(const ::nao_matador::Walking_msgsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nao_matador::Walking_msgsResponse> should match 
// service_traits::MD5Sum< ::nao_matador::Walking_msgs > 
template<>
struct MD5Sum< ::nao_matador::Walking_msgsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nao_matador::Walking_msgs >::value();
  }
  static const char* value(const ::nao_matador::Walking_msgsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nao_matador::Walking_msgsResponse> should match 
// service_traits::DataType< ::nao_matador::Walking_msgs > 
template<>
struct DataType< ::nao_matador::Walking_msgsResponse>
{
  static const char* value()
  {
    return DataType< ::nao_matador::Walking_msgs >::value();
  }
  static const char* value(const ::nao_matador::Walking_msgsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAO_MATADOR_MESSAGE_WALKING_MSGS_H
